<a href="https://colab.research.google.com/github/Akihiroflyfishing0127/Python_basic_kadai-/blob/main/data_analysis_basic_kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
multi_array_A = np.array([[0,1],[2,3],[4,5]])
multi_array_B = np.array([[0,1,2,3],[4,5,6,7]])

C = np.dot(multi_array_A,multi_array_B)
print(C)
print(C.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
